import Sidebar from '@/components/Sidebar';

export const metadata = {
    title: 'countries',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="">
                <div className="max-w-[1200px] min-h-screen bg-slate-100 mx-auto">
                    <nav className="w-full h-[50px] p-2 bg-blue-600"></nav>
                    <div className="h-full w-full flex">
                        <Sidebar />
                        <section className="w-[80%] h-full">{children}</section>
                    </div>
                </div>
            </body>
        </html>
    );
}

{
}
