import NavbarMobile from '@/components/NavbarMobile';
import NavbarPc from '@/components/NavbarPc';
import './globals.css';

export const metadata = {
    title: 'home',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="min-h-screen md:w-[1900px] w-screen md:flex bg-slate-50">
                <NavbarPc />
                <NavbarMobile />
                {children}
            </body>
        </html>
    );
}
