import './globals.css';
import ReduxProvider from './redux/ReduxProvider';

export const metadata = {
    title: 'home',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="">
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
